'''
Takes the collections json file generated by Postman and
returns only the query/mutation strings in a set.
'''

import os
import json
from typing import Dict


def collection_info() -> Dict:
  pass